// AUTO-GENERATED - DO NOT EDIT
// Generated by Claude from orris backend
// Source: github.com/orris-inc/orris/sdk/forward

// hub.go provides WebSocket-based hub connection functionality for forward agents.
// It handles real-time communication with the Orris server for status reporting,
// configuration synchronization, and probe task execution.
package forward

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"
	"sync"
	"time"

	"github.com/cenkalti/backoff/v5"
	"github.com/gorilla/websocket"
)

const (
	hubWriteWait  = 10 * time.Second
	hubPongWait   = 60 * time.Second
	hubPingPeriod = 30 * time.Second
)

// ReconnectConfig holds reconnection strategy parameters.
type ReconnectConfig struct {
	// InitialInterval is the first retry delay (default: 1s)
	InitialInterval time.Duration

	// MaxInterval is the maximum retry delay (default: 60s)
	MaxInterval time.Duration

	// MaxElapsedTime is the total time to keep retrying. 0 means never stop (default: 0)
	MaxElapsedTime time.Duration

	// Multiplier is the exponential backoff multiplier (default: 2.0)
	Multiplier float64

	// RandomizationFactor adds jitter to prevent thundering herd (default: 0.1)
	RandomizationFactor float64

	// OnConnected is called when successfully connected
	OnConnected func()

	// OnDisconnected is called when disconnected (with error)
	OnDisconnected func(err error)

	// OnReconnecting is called before each reconnection attempt
	OnReconnecting func(attempt uint64, delay time.Duration)

	// OnConfigSync is called when a config sync message is received from the server.
	// This is used to handle incremental or full configuration updates.
	OnConfigSync ConfigSyncHandler

	// OnAPIURLChanged is called when server notifies that API URL has changed.
	// The handler receives the new URL and reason, and should:
	// 1. Update local configuration file with the new URL
	// 2. Return nil to signal that RunHubLoopWithReconnect should exit
	//    so the caller can restart with the new URL
	// If the handler returns an error, the connection continues with current URL.
	OnAPIURLChanged func(newURL, reason string) error
}

// DefaultReconnectConfig returns the default reconnection configuration.
func DefaultReconnectConfig() *ReconnectConfig {
	return &ReconnectConfig{
		InitialInterval:     1 * time.Second,
		MaxInterval:         60 * time.Second,
		MaxElapsedTime:      0, // Never give up
		Multiplier:          2.0,
		RandomizationFactor: 0.1,
	}
}

// HubConn represents a WebSocket connection to the AgentHub.
type HubConn struct {
	conn   *websocket.Conn
	send   chan *HubMessage
	done   chan struct{}  // Signal channel for graceful shutdown
	Events chan *HubEvent // Event channel for agent to receive events
	mu     sync.Mutex     // Protects closed and send channel access
	closed bool

	// Message handler callback
	onMessage func(msg *HubMessage)
}

// HubMessage is the unified WebSocket message envelope.
type HubMessage struct {
	Type      string `json:"type"`
	AgentID   string `json:"agent_id,omitempty"` // Stripe-style prefixed ID (e.g., "fa_xK9mP2vL3nQ")
	Timestamp int64  `json:"timestamp"`
	Data      any    `json:"data,omitempty"`
}

// Hub message type constants define all WebSocket message types exchanged between agent and server.
//
// Message Flow:
//
//	Agent -> Server:
//	  - status:           Agent status report (CPU, memory, network, etc.)
//	  - heartbeat:        Keep-alive heartbeat
//	  - event:            Agent events (connected, disconnected, error, config_change)
//	  - probe_result:     Probe task execution result
//	  - config_ack:       Configuration sync acknowledgment
//	  - rule_sync_status: Rule sync and runtime status report
//
//	Server -> Agent:
//	  - command:          Server commands (reload_config, restart_rule, stop_rule, probe, update)
//	  - probe_task:       Probe task to execute
//	  - config_sync:      Configuration sync (full or incremental)
const (
	// Agent -> Server message types.
	MsgTypeStatus    = "status"    // Send agent status (AgentStatus)
	MsgTypeHeartbeat = "heartbeat" // Send heartbeat to keep connection alive
	MsgTypeEvent     = "event"     // Send agent events (AgentEventData)

	// Server -> Agent message types.
	MsgTypeCommand = "command" // Receive server commands (CommandData)

	// Probe message types.
	MsgTypeProbeTask   = "probe_task"   // Server -> Agent: receive probe task (ProbeTask)
	MsgTypeProbeResult = "probe_result" // Agent -> Server: send probe result (ProbeTaskResult)

	// Config sync message types.
	MsgTypeConfigSync = "config_sync" // Server -> Agent: receive config sync (ConfigSyncData)
	MsgTypeConfigAck  = "config_ack"  // Agent -> Server: send config acknowledgment (ConfigAckData)

	// Rule sync status message types.
	MsgTypeRuleSyncStatus = "rule_sync_status" // Agent -> Server: send rule sync status ([]RuleSyncStatusItem)

	// Tunnel health report message types.
	MsgTypeTunnelHealthReport = "tunnel_health_report" // Agent -> Server: report tunnel health status (TunnelHealthReport)
)

// CommandData represents a command sent from server to agent.
// Used with MsgTypeCommand message type.
type CommandData struct {
	CommandID string `json:"command_id"` // Unique command identifier
	Action    string `json:"action"`     // Command action (see CmdAction* constants)
	Payload   any    `json:"payload,omitempty"`
}

// Command action constants define available server commands.
//
// Supported Actions:
//   - reload_config:   Trigger agent to reload configuration from server
//   - restart_rule:    Restart a specific forward rule (Payload: rule_id string)
//   - stop_rule:       Stop a specific forward rule (Payload: rule_id string)
//   - probe:           Execute a probe task (Payload: ProbeTask)
//   - update:          Update agent binary to new version
//   - api_url_changed: API URL changed, agent should reconnect to new URL (Payload: APIURLChangedPayload)
const (
	CmdActionReloadConfig   = "reload_config"   // Reload configuration
	CmdActionRestartRule    = "restart_rule"    // Restart specific rule
	CmdActionStopRule       = "stop_rule"       // Stop specific rule
	CmdActionProbe          = "probe"           // Execute probe task
	CmdActionUpdate         = "update"          // Update agent binary
	CmdActionAPIURLChanged  = "api_url_changed" // API URL changed, reconnect to new URL
	CmdActionConfigRelocate = "config_relocate" // Configuration relocated to new server
)

// APIURLChangedPayload contains the new API URL for agent reconnection.
type APIURLChangedPayload struct {
	NewURL string `json:"new_url"` // New API base URL to connect to
	Reason string `json:"reason"`  // Reason for the change (e.g., "server migration")
}

// AgentEventData represents an agent event payload sent to server.
// Used with MsgTypeEvent message type via HubConn.SendEvent().
type AgentEventData struct {
	EventType string `json:"event_type"`        // Event type (see EventType* constants)
	Message   string `json:"message,omitempty"` // Human-readable message
	Extra     any    `json:"extra,omitempty"`   // Additional event-specific data
}

// Agent event type constants define events that agent can report to server.
//
// Supported Events:
//   - connected:     Agent successfully connected to hub
//   - disconnected:  Agent disconnected from hub
//   - error:         Agent encountered an error (Message contains error details)
//   - config_change: Agent configuration changed (Extra may contain change details)
//   - traffic:       Traffic data update (Extra contains TrafficEventData)
const (
	EventTypeConnected    = "connected"     // Agent connected
	EventTypeDisconnected = "disconnected"  // Agent disconnected
	EventTypeError        = "error"         // Error occurred
	EventTypeConfigChange = "config_change" // Configuration changed
	EventTypeTraffic      = "traffic"       // Traffic data update
)

// HubEventType represents the type of event received from server via HubConn.Events channel.
// These are high-level events that agents should handle for core functionality.
type HubEventType string

// HubEvent type constants define events received from server.
//
// Supported Events:
//   - config_sync:     Server pushed configuration update (full or incremental)
//   - probe_task:      Server requested agent to execute a probe task
//   - api_url_changed: Server notified API URL has changed, agent should reconnect
//
// Usage:
//
//	for event := range hubConn.Events {
//	    switch event.Type {
//	    case forward.HubEventConfigSync:
//	        // Handle config sync: event.ConfigSync contains the data
//	    case forward.HubEventProbeTask:
//	        // Handle probe task: event.ProbeTask contains the task
//	    case forward.HubEventAPIURLChanged:
//	        // Handle API URL change: event.APIURLChanged contains new URL
//	    }
//	}
const (
	HubEventConfigSync    HubEventType = "config_sync"     // Configuration sync from server
	HubEventProbeTask     HubEventType = "probe_task"      // Probe task from server
	HubEventAPIURLChanged HubEventType = "api_url_changed" // API URL changed notification
)

// HubEvent is a unified event structure delivered via HubConn.Events channel.
// Check the Type field to determine which data field is populated.
type HubEvent struct {
	Type          HubEventType          // Event type
	ConfigSync    *ConfigSyncData       // Populated when Type == HubEventConfigSync
	ProbeTask     *ProbeTask            // Populated when Type == HubEventProbeTask
	APIURLChanged *APIURLChangedPayload // Populated when Type == HubEventAPIURLChanged
}

// ConfigSyncData represents configuration synchronization data.
type ConfigSyncData struct {
	Version          uint64         `json:"version"`
	FullSync         bool           `json:"full_sync"`
	Added            []RuleSyncData `json:"added,omitempty"`
	Updated          []RuleSyncData `json:"updated,omitempty"`
	Removed          []string       `json:"removed,omitempty"`           // Rule IDs to remove (Stripe-style prefixed, e.g., "fr_xxx")
	ClientToken      string         `json:"client_token,omitempty"`      // Agent's token for tunnel handshake (full sync only)
	BlockedProtocols []string       `json:"blocked_protocols,omitempty"` // Agent-level blocked protocols (supports incremental sync)
	// Note: TokenSigningSecret has been removed for security reasons.
	// Agents should verify tokens via the server API, not using local HMAC verification.
}

// ExitAgentSyncData represents an exit agent with connection info for load balancing.
type ExitAgentSyncData struct {
	AgentID string `json:"agent_id"` // Stripe-style prefixed ID
	Weight  uint16 `json:"weight"`   // Load balancing weight (0-100, 0=backup)
	Address string `json:"address"`  // Exit agent public address
	WsPort  uint16 `json:"ws_port"`  // Exit agent WebSocket port
	TlsPort uint16 `json:"tls_port"` // Exit agent TLS port
	Online  bool   `json:"online"`   // Exit agent online status
}

// HealthCheckConfig represents health check configuration for load balancing failover.
type HealthCheckConfig struct {
	UnhealthyThreshold uint32 `json:"unhealthy_threshold"` // Number of failures before marking unhealthy (default: 2)
	HealthyThreshold   uint32 `json:"healthy_threshold"`   // Number of successes before marking healthy (default: 1)
}

// RuleSyncData represents rule synchronization data (aligned with server DTO).
type RuleSyncData struct {
	ID                     string   `json:"id"`       // Stripe-style prefixed ID (e.g., "fr_xK9mP2vL3nQ")
	ShortID                string   `json:"short_id"` // Deprecated: use ID instead
	RuleType               string   `json:"rule_type"`
	ListenPort             uint16   `json:"listen_port"`
	ListenIP               string   `json:"listen_ip,omitempty"`
	TargetAddress          string   `json:"target_address,omitempty"`
	TargetPort             uint16   `json:"target_port,omitempty"`
	BindIP                 string   `json:"bind_ip,omitempty"` // Bind IP address for outbound connections
	Protocol               string   `json:"protocol"`
	TunnelType             string   `json:"tunnel_type,omitempty"` // Tunnel type: "ws" or "tls" (default: "ws")
	Role                   string   `json:"role,omitempty"`
	AgentID                string   `json:"agent_id,omitempty"` // Entry agent ID (for exit agents to verify handshake)
	NextHopAgentID         string   `json:"next_hop_agent_id,omitempty"`
	NextHopAddress         string   `json:"next_hop_address,omitempty"`
	NextHopWsPort          uint16   `json:"next_hop_ws_port,omitempty"`
	NextHopTlsPort         uint16   `json:"next_hop_tls_port,omitempty"`         // Next agent's TLS port
	NextHopPort            uint16   `json:"next_hop_port,omitempty"`             // Next agent's listen port for direct_chain
	NextHopConnectionToken string   `json:"next_hop_connection_token,omitempty"` // Short-term token for next hop authentication
	AddressPreference      string   `json:"address_preference,omitempty"`        // Address preference for next hop: auto, public, tunnel
	TunnelHops             *int     `json:"tunnel_hops,omitempty"`               // Number of hops using tunnel (nil=full tunnel)
	HopMode                string   `json:"hop_mode,omitempty"`                  // Hop mode: "tunnel", "direct", or "boundary"
	InboundMode            string   `json:"inbound_mode,omitempty"`              // For boundary nodes: inbound mode
	OutboundMode           string   `json:"outbound_mode,omitempty"`             // For boundary nodes: outbound mode
	ChainAgentIDs          []string `json:"chain_agent_ids,omitempty"`
	ChainPosition          int      `json:"chain_position,omitempty"`
	IsLastInChain          bool     `json:"is_last_in_chain,omitempty"`
	// Multiple exit agents for load balancing (entry rules only, mutually exclusive with NextHop* fields)
	ExitAgents          []ExitAgentSyncData `json:"exit_agents,omitempty"`
	LoadBalanceStrategy string              `json:"load_balance_strategy,omitempty"` // Load balance strategy: "failover" (default), "weighted"
	HealthCheck         *HealthCheckConfig  `json:"health_check,omitempty"`          // Health check config for load balancing failover
}

// ConfigAckData represents configuration acknowledgment data.
type ConfigAckData struct {
	Version uint64 `json:"version"`
	Success bool   `json:"success"`
	Error   string `json:"error,omitempty"`
}

// TrafficEventData represents traffic data sent via EventTypeTraffic event.
// This is the payload structure for the Extra field when sending traffic updates.
//
// Usage:
//
//	hubConn.SendEvent(forward.EventTypeTraffic, "", &forward.TrafficEventData{
//	    Rules: []forward.TrafficItem{
//	        {RuleID: "fr_xxx", UploadBytes: 1024, DownloadBytes: 2048},
//	    },
//	})
type TrafficEventData struct {
	Rules []TrafficItem `json:"rules"` // Traffic data for each rule
}

// ConnectHub establishes a WebSocket connection to the AgentHub.
// The connection allows the agent to receive commands and send status updates.
func (c *Client) ConnectHub(ctx context.Context) (*HubConn, error) {
	wsURL, err := c.buildHubWSURL()
	if err != nil {
		return nil, fmt.Errorf("build websocket url: %w", err)
	}

	dialer := websocket.Dialer{
		HandshakeTimeout: 10 * time.Second,
	}

	conn, resp, err := dialer.DialContext(ctx, wsURL, nil)
	if err != nil {
		if resp != nil {
			return nil, fmt.Errorf("websocket dial failed: status=%d, err=%w", resp.StatusCode, err)
		}
		return nil, fmt.Errorf("websocket dial: %w", err)
	}

	hubConn := &HubConn{
		conn:   conn,
		send:   make(chan *HubMessage, 256),
		done:   make(chan struct{}),
		Events: make(chan *HubEvent, 256),
		closed: false,
	}

	return hubConn, nil
}

// buildHubWSURL builds the WebSocket URL for hub connection.
func (c *Client) buildHubWSURL() (string, error) {
	u, err := url.Parse(c.baseURL)
	if err != nil {
		return "", fmt.Errorf("parse base url: %w", err)
	}

	// Convert http(s) to ws(s)
	switch u.Scheme {
	case "https":
		u.Scheme = "wss"
	case "http":
		u.Scheme = "ws"
	default:
		u.Scheme = "wss"
	}

	// Build path: /ws/forward-agent
	u.Path = strings.TrimSuffix(u.Path, "/") + "/ws/forward-agent"

	// Add token as query parameter
	q := u.Query()
	q.Set("token", c.token)
	u.RawQuery = q.Encode()

	return u.String(), nil
}

// SetMessageHandler sets the callback for incoming messages.
func (hc *HubConn) SetMessageHandler(handler func(msg *HubMessage)) {
	hc.onMessage = handler
}

// Send sends a message to the server.
func (hc *HubConn) Send(msg *HubMessage) error {
	hc.mu.Lock()
	defer hc.mu.Unlock()

	if hc.closed {
		return ErrConnectionClosed
	}

	select {
	case hc.send <- msg:
		return nil
	default:
		return fmt.Errorf("send channel full")
	}
}

// SendStatus sends a status update to the server.
func (hc *HubConn) SendStatus(status *AgentStatus) error {
	msg := &HubMessage{
		Type:      MsgTypeStatus,
		Timestamp: time.Now().Unix(),
		Data:      status,
	}
	return hc.Send(msg)
}

// SendProbeResult sends a probe result to the server.
func (hc *HubConn) SendProbeResult(result *ProbeTaskResult) error {
	msg := &HubMessage{
		Type:      MsgTypeProbeResult,
		Timestamp: time.Now().Unix(),
		Data:      result,
	}
	return hc.Send(msg)
}

// SendConfigAck sends a configuration acknowledgment to the server.
func (hc *HubConn) SendConfigAck(ack *ConfigAckData) error {
	msg := &HubMessage{
		Type:      MsgTypeConfigAck,
		Timestamp: time.Now().Unix(),
		Data:      ack,
	}
	return hc.Send(msg)
}

// SendRuleSyncStatus sends rule sync status to the server.
func (hc *HubConn) SendRuleSyncStatus(rules []RuleSyncStatusItem) error {
	msg := &HubMessage{
		Type:      MsgTypeRuleSyncStatus,
		Timestamp: time.Now().Unix(),
		Data: map[string]any{
			"rules": rules,
		},
	}
	return hc.Send(msg)
}

// SendEvent sends an event to the server.
func (hc *HubConn) SendEvent(eventType, message string, extra any) error {
	msg := &HubMessage{
		Type:      MsgTypeEvent,
		Timestamp: time.Now().Unix(),
		Data: map[string]any{
			"event_type": eventType,
			"message":    message,
			"extra":      extra,
		},
	}
	return hc.Send(msg)
}

// SendTunnelHealthReport sends a tunnel health status report to the server.
// Entry agents should call this when they detect tunnel health changes to exit agents.
// The server will notify other entry agents to update their load balancing decisions.
func (hc *HubConn) SendTunnelHealthReport(report *TunnelHealthReport) error {
	msg := &HubMessage{
		Type:      MsgTypeTunnelHealthReport,
		Timestamp: time.Now().Unix(),
		Data:      report,
	}
	return hc.Send(msg)
}

// Run starts the read and write pumps. This blocks until the connection is closed.
func (hc *HubConn) Run(ctx context.Context) error {
	errChan := make(chan error, 2)

	// Start write pump
	go func() {
		errChan <- hc.writePump(ctx)
	}()

	// Start read pump
	go func() {
		errChan <- hc.readPump(ctx)
	}()

	// Wait for either pump to exit
	err := <-errChan
	hc.Close()
	return err
}

// readPump reads messages from the WebSocket.
func (hc *HubConn) readPump(ctx context.Context) error {
	hc.conn.SetReadLimit(65536)
	hc.conn.SetReadDeadline(time.Now().Add(hubPongWait))
	hc.conn.SetPongHandler(func(string) error {
		hc.conn.SetReadDeadline(time.Now().Add(hubPongWait))
		return nil
	})

	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		_, message, err := hc.conn.ReadMessage()
		if err != nil {
			return fmt.Errorf("read message: %w", err)
		}

		var msg HubMessage
		if err := json.Unmarshal(message, &msg); err != nil {
			continue // Skip malformed messages
		}

		// Convert message to event and send to Events channel
		hc.dispatchEvent(&msg)

		// Also call legacy onMessage handler for backward compatibility
		if hc.onMessage != nil {
			hc.onMessage(&msg)
		}
	}
}

// dispatchEvent converts HubMessage to HubEvent and sends to Events channel.
func (hc *HubConn) dispatchEvent(msg *HubMessage) {
	var event *HubEvent

	switch msg.Type {
	case MsgTypeConfigSync:
		configSync := parseConfigSync(msg.Data)
		if configSync != nil {
			event = &HubEvent{
				Type:       HubEventConfigSync,
				ConfigSync: configSync,
			}
		}
	case MsgTypeProbeTask:
		probeTask := parseProbeTask(msg.Data)
		if probeTask != nil {
			event = &HubEvent{
				Type:      HubEventProbeTask,
				ProbeTask: probeTask,
			}
		}
	case MsgTypeCommand:
		cmd := parseCommand(msg.Data)
		if cmd != nil && cmd.Action == CmdActionAPIURLChanged {
			payload := parseAPIURLChangedPayload(cmd.Payload)
			if payload != nil {
				event = &HubEvent{
					Type:          HubEventAPIURLChanged,
					APIURLChanged: payload,
				}
			}
		}
	default:
		// Ignore other message types for event channel
		return
	}

	if event != nil {
		select {
		case hc.Events <- event:
		default:
			// Event channel full, skip this event to avoid blocking
		}
	}
}

// parseCommand parses command data from message data.
func parseCommand(data any) *CommandData {
	dataBytes, err := json.Marshal(data)
	if err != nil {
		return nil
	}

	var cmd CommandData
	if err := json.Unmarshal(dataBytes, &cmd); err != nil {
		return nil
	}
	return &cmd
}

// parseAPIURLChangedPayload parses API URL changed payload from command payload.
func parseAPIURLChangedPayload(payload any) *APIURLChangedPayload {
	dataBytes, err := json.Marshal(payload)
	if err != nil {
		return nil
	}

	var p APIURLChangedPayload
	if err := json.Unmarshal(dataBytes, &p); err != nil {
		return nil
	}
	return &p
}

// parseConfigSync parses config sync data from message data.
func parseConfigSync(data any) *ConfigSyncData {
	dataBytes, err := json.Marshal(data)
	if err != nil {
		return nil
	}

	var configSync ConfigSyncData
	if err := json.Unmarshal(dataBytes, &configSync); err != nil {
		return nil
	}
	return &configSync
}

// writePump writes messages to the WebSocket.
// All writes to the websocket connection are done here to avoid concurrent writes.
func (hc *HubConn) writePump(ctx context.Context) error {
	ticker := time.NewTicker(hubPingPeriod)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			// Context canceled, send close message and exit
			hc.conn.SetWriteDeadline(time.Now().Add(hubWriteWait))
			hc.conn.WriteMessage(websocket.CloseMessage,
				websocket.FormatCloseMessage(websocket.CloseNormalClosure, ""))
			return ctx.Err()

		case <-hc.done:
			// Graceful shutdown requested, send close message
			hc.conn.SetWriteDeadline(time.Now().Add(hubWriteWait))
			hc.conn.WriteMessage(websocket.CloseMessage,
				websocket.FormatCloseMessage(websocket.CloseNormalClosure, ""))
			return nil

		case msg, ok := <-hc.send:
			if !ok {
				// Send channel closed, should not happen as we use done channel
				return nil
			}
			hc.conn.SetWriteDeadline(time.Now().Add(hubWriteWait))
			if err := hc.conn.WriteJSON(msg); err != nil {
				return fmt.Errorf("write message: %w", err)
			}

		case <-ticker.C:
			hc.conn.SetWriteDeadline(time.Now().Add(hubWriteWait))
			if err := hc.conn.WriteMessage(websocket.PingMessage, nil); err != nil {
				return fmt.Errorf("ping: %w", err)
			}
		}
	}
}

// Close closes the hub connection.
// It signals the writePump to send close message and shutdown gracefully.
func (hc *HubConn) Close() error {
	hc.mu.Lock()
	if hc.closed {
		hc.mu.Unlock()
		return nil
	}
	hc.closed = true
	close(hc.done) // Signal writePump to shutdown and send close message
	hc.mu.Unlock()

	// Close Events channel (safe to close from any goroutine)
	// Note: send channel is not closed here to avoid send-on-closed-channel panic
	// writePump will exit via done channel
	close(hc.Events)

	return hc.conn.Close()
}

// IsClosed returns true if the connection is closed.
func (hc *HubConn) IsClosed() bool {
	hc.mu.Lock()
	defer hc.mu.Unlock()
	return hc.closed
}

// HubMessageHandler is a callback function for handling hub messages.
type HubMessageHandler func(msg *HubMessage)

// ProbeTaskHandler is a callback function for handling probe tasks.
// Returns the probe result to be sent back to the server.
type ProbeTaskHandler func(task *ProbeTask) *ProbeTaskResult

// ConfigSyncHandler is a callback function for handling config sync events.
// The handler receives the config sync data and should return an error if processing failed.
type ConfigSyncHandler func(data *ConfigSyncData) error

// RunHubLoop connects to the hub and handles messages.
// This is a convenience method that manages the connection lifecycle without reconnection.
// For production use, prefer RunHubLoopWithReconnect which handles automatic reconnection.
func (c *Client) RunHubLoop(ctx context.Context, probeHandler ProbeTaskHandler) error {
	conn, err := c.ConnectHub(ctx)
	if err != nil {
		return fmt.Errorf("connect hub: %w", err)
	}
	defer conn.Close()

	// Set up message handler
	conn.SetMessageHandler(func(msg *HubMessage) {
		switch msg.Type {
		case MsgTypeProbeTask:
			if probeHandler != nil {
				go func() {
					task := parseProbeTask(msg.Data)
					if task != nil {
						result := probeHandler(task)
						if result != nil {
							conn.SendProbeResult(result)
						}
					}
				}()
			}
		case MsgTypeCommand:
			// Handle commands if needed
		}
	})

	// Run the connection
	return conn.Run(ctx)
}

// parseProbeTask parses probe task from message data.
func parseProbeTask(data any) *ProbeTask {
	dataBytes, err := json.Marshal(data)
	if err != nil {
		return nil
	}

	var task ProbeTask
	if err := json.Unmarshal(dataBytes, &task); err != nil {
		return nil
	}
	return &task
}

// RunHubLoopWithReconnect connects to the hub with automatic reconnection.
// It uses exponential backoff strategy to retry failed connections.
// The probeHandler is called when a probe task is received.
// This method blocks until the context is canceled or API URL changes.
//
// Use the ReconnectConfig callbacks to handle connection events:
//   - OnConnected: called when successfully connected
//   - OnDisconnected: called when disconnected (with error)
//   - OnReconnecting: called before each reconnection attempt
//   - OnAPIURLChanged: called when server notifies API URL change
//
// Returns:
//   - context.Canceled if context is canceled
//   - *APIURLChangedError if server notifies API URL change (caller should restart with new URL)
//   - other errors for connection failures
func (c *Client) RunHubLoopWithReconnect(ctx context.Context, probeHandler ProbeTaskHandler, config *ReconnectConfig) error {
	if config == nil {
		config = DefaultReconnectConfig()
	}

	// Create exponential backoff strategy
	expBackoff := backoff.NewExponentialBackOff()
	expBackoff.InitialInterval = config.InitialInterval
	expBackoff.MaxInterval = config.MaxInterval
	expBackoff.Multiplier = config.Multiplier
	expBackoff.RandomizationFactor = config.RandomizationFactor
	expBackoff.Reset()

	var attempt uint64
	startTime := time.Now()

	// Reconnection loop
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		attempt++

		// Attempt to connect and run
		err := c.runHubLoopOnce(ctx, probeHandler, config)

		// Check if API URL changed - return immediately so caller can restart with new URL
		if IsAPIURLChanged(err) {
			return err
		}

		// Connection ended, call disconnect callback
		if config.OnDisconnected != nil {
			config.OnDisconnected(err)
		}

		// If context was canceled, exit immediately
		if ctx.Err() != nil {
			return ctx.Err()
		}

		// Check max elapsed time
		if config.MaxElapsedTime > 0 && time.Since(startTime) >= config.MaxElapsedTime {
			return fmt.Errorf("reconnection failed after %v: %w", config.MaxElapsedTime, err)
		}

		// Calculate next backoff delay
		delay := expBackoff.NextBackOff()
		if delay == backoff.Stop {
			return fmt.Errorf("reconnection failed: %w", err)
		}

		// Call reconnecting callback with attempt info
		if config.OnReconnecting != nil {
			config.OnReconnecting(attempt, delay)
		}

		// Wait before reconnecting
		timer := time.NewTimer(delay)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
			// Continue to next connection attempt
		}
	}
}

// runHubLoopOnce executes a single hub connection lifecycle.
func (c *Client) runHubLoopOnce(ctx context.Context, probeHandler ProbeTaskHandler, config *ReconnectConfig) error {
	conn, err := c.ConnectHub(ctx)
	if err != nil {
		return fmt.Errorf("connect hub: %w", err)
	}
	defer conn.Close()

	// Call connected callback
	if config.OnConnected != nil {
		config.OnConnected()
	}

	// Create a cancellable context for API URL change handling
	connCtx, cancel := context.WithCancel(ctx)
	defer cancel()

	// Channel to receive API URL change error
	apiURLChangedCh := make(chan *APIURLChangedError, 1)

	// Set up message handler
	conn.SetMessageHandler(func(msg *HubMessage) {
		switch msg.Type {
		case MsgTypeProbeTask:
			if probeHandler != nil {
				go func() {
					task := parseProbeTask(msg.Data)
					if task != nil {
						result := probeHandler(task)
						if result != nil {
							conn.SendProbeResult(result)
						}
					}
				}()
			}
		case MsgTypeConfigSync:
			if config.OnConfigSync != nil {
				go func() {
					configSync := parseConfigSync(msg.Data)
					if configSync != nil {
						err := config.OnConfigSync(configSync)
						// Send acknowledgment back to server
						ack := &ConfigAckData{
							Version: configSync.Version,
							Success: err == nil,
						}
						if err != nil {
							ack.Error = err.Error()
						}
						conn.SendConfigAck(ack)
					}
				}()
			}
		case MsgTypeCommand:
			cmd := parseCommand(msg.Data)
			if cmd == nil {
				return
			}
			switch cmd.Action {
			case CmdActionAPIURLChanged:
				payload := parseAPIURLChangedPayload(cmd.Payload)
				if payload != nil {
					// Call the handler if provided
					if config.OnAPIURLChanged != nil {
						if err := config.OnAPIURLChanged(payload.NewURL, payload.Reason); err == nil {
							// Handler succeeded, signal to exit with API URL changed error
							select {
							case apiURLChangedCh <- &APIURLChangedError{
								NewURL: payload.NewURL,
								Reason: payload.Reason,
							}:
							default:
							}
							cancel() // Cancel the connection context
						}
					}
				}
			}
		}
	})

	// Run the connection (blocks until disconnected)
	err = conn.Run(connCtx)

	// Check if we exited due to API URL change
	select {
	case apiErr := <-apiURLChangedCh:
		return apiErr
	default:
	}

	return err
}
