// AUTO-GENERATED - DO NOT EDIT
// Generated by Claude from orris backend
// Source: github.com/orris-inc/orris/sdk/forward

package forward

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net"
	"net/http"
	"net/url"
	"time"

	"github.com/gorilla/websocket"
	utls "github.com/refraction-networking/utls"
)

// TunnelPingResult contains the results of a tunnel ping operation.
type TunnelPingResult struct {
	Success      bool
	MinLatencyMs int64
	MaxLatencyMs int64
	AvgLatencyMs int64
	PacketLoss   float64
	PingsSent    int
	PingsRecv    int
	Error        string
}

// TunnelPinger performs ping operations through a tunnel connection.
type TunnelPinger struct {
	target     string
	port       uint16
	tunnelType TunnelType
	token      string
	ruleID     string

	pingCount      int
	pingIntervalMs int
	connTimeout    time.Duration
	pingTimeout    time.Duration
}

// TunnelPingerOption is a functional option for TunnelPinger.
type TunnelPingerOption func(*TunnelPinger)

// WithPingCount sets the number of pings to send.
func WithPingCount(count int) TunnelPingerOption {
	return func(p *TunnelPinger) {
		if count > 0 {
			p.pingCount = count
		}
	}
}

// WithPingInterval sets the interval between pings.
func WithPingInterval(ms int) TunnelPingerOption {
	return func(p *TunnelPinger) {
		if ms > 0 {
			p.pingIntervalMs = ms
		}
	}
}

// WithConnTimeout sets the connection timeout.
func WithConnTimeout(timeout time.Duration) TunnelPingerOption {
	return func(p *TunnelPinger) {
		if timeout > 0 {
			p.connTimeout = timeout
		}
	}
}

// WithPingTimeout sets the timeout for each ping.
func WithPingTimeout(timeout time.Duration) TunnelPingerOption {
	return func(p *TunnelPinger) {
		if timeout > 0 {
			p.pingTimeout = timeout
		}
	}
}

// NewTunnelPinger creates a new TunnelPinger.
func NewTunnelPinger(target string, port uint16, tunnelType TunnelType, token, ruleID string, opts ...TunnelPingerOption) *TunnelPinger {
	p := &TunnelPinger{
		target:         target,
		port:           port,
		tunnelType:     tunnelType,
		token:          token,
		ruleID:         ruleID,
		pingCount:      3,
		pingIntervalMs: 200,
		connTimeout:    10 * time.Second,
		pingTimeout:    5 * time.Second,
	}

	for _, opt := range opts {
		opt(p)
	}

	return p
}

// Ping performs the tunnel ping operation and returns the results.
func (p *TunnelPinger) Ping(ctx context.Context) *TunnelPingResult {
	if p.tunnelType.IsTLS() {
		return p.pingTLS(ctx)
	}
	return p.pingWS(ctx)
}

// Tunnel protocol message types (must match tunnel/protocol.go on client side)
const (
	tunnelMsgPing = 4
	tunnelMsgPong = 5
)

// Tunnel protocol header size: type(1) + connID(8) + length(4) = 13 bytes
const tunnelHeaderSize = 13

// pingWS performs ping through WebSocket tunnel using tunnel protocol messages.
func (p *TunnelPinger) pingWS(ctx context.Context) *TunnelPingResult {
	result := &TunnelPingResult{
		PingsSent: p.pingCount,
	}

	// Build WebSocket URL - use wss:// with uTLS
	hostPort := net.JoinHostPort(p.target, fmt.Sprintf("%d", p.port))
	wsURL := fmt.Sprintf("wss://%s/tunnel", hostPort)

	// Create dialer with uTLS for wss:// connections
	dialer := websocket.Dialer{
		HandshakeTimeout: p.connTimeout,
		NetDialTLSContext: func(ctx context.Context, network, addr string) (net.Conn, error) {
			var d net.Dialer
			tcpConn, err := d.DialContext(ctx, network, addr)
			if err != nil {
				return nil, err
			}
			tlsConfig := &utls.Config{
				InsecureSkipVerify: true,
			}
			tlsConn := utls.UClient(tcpConn, tlsConfig, utls.HelloChrome_Auto)
			if err := tlsConn.Handshake(); err != nil {
				tcpConn.Close()
				return nil, err
			}
			return tlsConn, nil
		},
	}

	// Parse URL
	u, err := url.Parse(wsURL)
	if err != nil {
		result.Error = fmt.Sprintf("parse url: %v", err)
		return result
	}

	// Connect
	connCtx, connCancel := context.WithTimeout(ctx, p.connTimeout)
	defer connCancel()

	conn, resp, err := dialer.DialContext(connCtx, u.String(), http.Header{})
	if err != nil {
		if resp != nil {
			result.Error = fmt.Sprintf("dial failed: status=%d, err=%v", resp.StatusCode, err)
		} else {
			result.Error = fmt.Sprintf("dial: %v", err)
		}
		return result
	}
	defer p.closeWSConn(conn)

	// Perform tunnel handshake (JSON format)
	handshake := TunnelHandshake{
		AgentToken: p.token,
		RuleID:     p.ruleID,
		IsProbe:    true,
	}
	handshakeData, _ := json.Marshal(handshake)
	if err := conn.WriteMessage(websocket.TextMessage, handshakeData); err != nil {
		result.Error = fmt.Sprintf("write handshake: %v", err)
		return result
	}

	// Read handshake response
	conn.SetReadDeadline(time.Now().Add(p.connTimeout))
	_, respData, err := conn.ReadMessage()
	if err != nil {
		result.Error = fmt.Sprintf("read handshake response: %v", err)
		return result
	}
	conn.SetReadDeadline(time.Time{})

	var handshakeResult TunnelHandshakeResult
	if err := json.Unmarshal(respData, &handshakeResult); err != nil {
		result.Error = fmt.Sprintf("parse handshake result: %v", err)
		return result
	}

	if !handshakeResult.Success {
		result.Error = fmt.Sprintf("handshake failed: %s", handshakeResult.Error)
		return result
	}

	// Perform pings using tunnel protocol MsgPing/MsgPong
	latencies := make([]int64, 0, p.pingCount)

	for i := 0; i < p.pingCount; i++ {
		select {
		case <-ctx.Done():
			result.Error = ctx.Err().Error()
			return result
		default:
		}

		latency, err := p.sendWSProtocolPing(conn)
		if err == nil {
			latencies = append(latencies, latency)
		}

		// Wait interval before next ping (except for last one)
		if i < p.pingCount-1 {
			time.Sleep(time.Duration(p.pingIntervalMs) * time.Millisecond)
		}
	}

	return p.calculateResults(latencies)
}

// closeWSConn closes a WebSocket connection gracefully by sending a close frame first.
func (p *TunnelPinger) closeWSConn(conn *websocket.Conn) {
	// Send close frame for graceful shutdown
	conn.WriteMessage(websocket.CloseMessage,
		websocket.FormatCloseMessage(websocket.CloseNormalClosure, ""))
	conn.Close()
}

// sendWSProtocolPing sends a tunnel protocol ping through WebSocket and measures RTT.
func (p *TunnelPinger) sendWSProtocolPing(conn *websocket.Conn) (int64, error) {
	start := time.Now()

	// Build ping message using tunnel protocol format: [type:1][connID:8][length:4]
	pingMsg := make([]byte, tunnelHeaderSize)
	pingMsg[0] = tunnelMsgPing
	// connID = 0 for ping (bytes 1-8 already zeroed)
	// length = 0 for ping (bytes 9-12 already zeroed)

	// Set deadlines
	deadline := start.Add(p.pingTimeout)
	if err := conn.SetWriteDeadline(deadline); err != nil {
		return 0, err
	}
	if err := conn.SetReadDeadline(deadline); err != nil {
		return 0, err
	}

	// Send ping as binary message
	if err := conn.WriteMessage(websocket.BinaryMessage, pingMsg); err != nil {
		return 0, fmt.Errorf("write ping: %w", err)
	}

	// Read pong message
	msgType, respData, err := conn.ReadMessage()
	if err != nil {
		return 0, fmt.Errorf("read pong: %w", err)
	}

	if msgType != websocket.BinaryMessage {
		return 0, fmt.Errorf("unexpected message type: %d", msgType)
	}

	if len(respData) < tunnelHeaderSize {
		return 0, fmt.Errorf("response too short: %d bytes", len(respData))
	}

	// Verify message type is pong
	if respData[0] != tunnelMsgPong {
		return 0, fmt.Errorf("unexpected protocol message type: %d", respData[0])
	}

	return time.Since(start).Milliseconds(), nil
}

// pingTLS performs ping through TLS tunnel using tunnel protocol.
func (p *TunnelPinger) pingTLS(ctx context.Context) *TunnelPingResult {
	result := &TunnelPingResult{
		PingsSent: p.pingCount,
	}

	// Connect with uTLS (use net.JoinHostPort to handle IPv6 addresses correctly)
	addr := net.JoinHostPort(p.target, fmt.Sprintf("%d", p.port))
	dialer := &net.Dialer{
		Timeout: p.connTimeout,
	}

	connCtx, connCancel := context.WithTimeout(ctx, p.connTimeout)
	defer connCancel()

	tcpConn, err := dialer.DialContext(connCtx, "tcp", addr)
	if err != nil {
		result.Error = fmt.Sprintf("tcp dial: %v", err)
		return result
	}

	tlsConfig := &utls.Config{
		InsecureSkipVerify: true,
	}
	tlsConn := utls.UClient(tcpConn, tlsConfig, utls.HelloChrome_Auto)
	if err := tlsConn.Handshake(); err != nil {
		tcpConn.Close()
		result.Error = fmt.Sprintf("tls handshake: %v", err)
		return result
	}
	defer tlsConn.Close()

	// Check context
	select {
	case <-connCtx.Done():
		result.Error = connCtx.Err().Error()
		return result
	default:
	}

	// Send handshake
	handshake := TunnelHandshake{
		AgentToken: p.token,
		RuleID:     p.ruleID,
		IsProbe:    true,
	}
	handshakeData, _ := json.Marshal(handshake)

	// Write handshake length + data
	if err := tlsConn.SetWriteDeadline(time.Now().Add(p.connTimeout)); err != nil {
		result.Error = fmt.Sprintf("set write deadline: %v", err)
		return result
	}

	// Write length (4 bytes, big endian)
	length := uint32(len(handshakeData))
	lengthBuf := []byte{byte(length >> 24), byte(length >> 16), byte(length >> 8), byte(length)}
	if _, err := tlsConn.Write(lengthBuf); err != nil {
		result.Error = fmt.Sprintf("write handshake length: %v", err)
		return result
	}
	if _, err := tlsConn.Write(handshakeData); err != nil {
		result.Error = fmt.Sprintf("write handshake: %v", err)
		return result
	}

	// Read handshake response
	if err := tlsConn.SetReadDeadline(time.Now().Add(p.connTimeout)); err != nil {
		result.Error = fmt.Sprintf("set read deadline: %v", err)
		return result
	}

	respLengthBuf := make([]byte, 4)
	if _, err := io.ReadFull(tlsConn, respLengthBuf); err != nil {
		result.Error = fmt.Sprintf("read response length: %v", err)
		return result
	}
	respLength := uint32(respLengthBuf[0])<<24 | uint32(respLengthBuf[1])<<16 |
		uint32(respLengthBuf[2])<<8 | uint32(respLengthBuf[3])

	if respLength > 4096 {
		result.Error = "response too large"
		return result
	}

	respData := make([]byte, respLength)
	if _, err := io.ReadFull(tlsConn, respData); err != nil {
		result.Error = fmt.Sprintf("read response: %v", err)
		return result
	}

	var handshakeResult TunnelHandshakeResult
	if err := json.Unmarshal(respData, &handshakeResult); err != nil {
		result.Error = fmt.Sprintf("parse handshake result: %v", err)
		return result
	}

	if !handshakeResult.Success {
		result.Error = fmt.Sprintf("handshake failed: %s", handshakeResult.Error)
		return result
	}

	// Perform tunnel protocol pings using MsgPing/MsgPong
	latencies := make([]int64, 0, p.pingCount)

	for i := 0; i < p.pingCount; i++ {
		select {
		case <-ctx.Done():
			result.Error = ctx.Err().Error()
			return result
		default:
		}

		latency, err := p.sendTLSPing(tlsConn)
		if err == nil {
			latencies = append(latencies, latency)
		}

		// Wait interval before next ping (except for last one)
		if i < p.pingCount-1 {
			time.Sleep(time.Duration(p.pingIntervalMs) * time.Millisecond)
		}
	}

	return p.calculateResults(latencies)
}

// sendTLSPing sends a ping through TLS connection using tunnel protocol and measures RTT.
func (p *TunnelPinger) sendTLSPing(conn net.Conn) (int64, error) {
	start := time.Now()

	// Set deadlines
	deadline := start.Add(p.pingTimeout)
	if err := conn.SetWriteDeadline(deadline); err != nil {
		return 0, err
	}
	if err := conn.SetReadDeadline(deadline); err != nil {
		return 0, err
	}

	// Build ping message using tunnel protocol format: [type:1][connID:8][length:4]
	pingMsg := make([]byte, tunnelHeaderSize)
	pingMsg[0] = tunnelMsgPing
	// connID = 0 for ping (bytes 1-8 already zeroed)
	// length = 0 for ping (bytes 9-12 already zeroed)

	if _, err := conn.Write(pingMsg); err != nil {
		return 0, fmt.Errorf("write ping: %w", err)
	}

	// Read pong message header using io.ReadFull to ensure complete read
	respHeader := make([]byte, tunnelHeaderSize)
	if _, err := io.ReadFull(conn, respHeader); err != nil {
		return 0, fmt.Errorf("read pong: %w", err)
	}

	// Verify message type is pong
	if respHeader[0] != tunnelMsgPong {
		return 0, fmt.Errorf("unexpected message type: %d", respHeader[0])
	}

	// Check payload length and read if present (should be 0 for pong)
	payloadLen := uint32(respHeader[9])<<24 | uint32(respHeader[10])<<16 |
		uint32(respHeader[11])<<8 | uint32(respHeader[12])
	if payloadLen > 0 {
		payload := make([]byte, payloadLen)
		if _, err := io.ReadFull(conn, payload); err != nil {
			return 0, fmt.Errorf("read pong payload: %w", err)
		}
	}

	return time.Since(start).Milliseconds(), nil
}

// calculateResults calculates statistics from latency samples.
func (p *TunnelPinger) calculateResults(latencies []int64) *TunnelPingResult {
	result := &TunnelPingResult{
		PingsSent: p.pingCount,
		PingsRecv: len(latencies),
	}

	if len(latencies) == 0 {
		result.PacketLoss = 100.0
		result.Error = "all pings failed"
		return result
	}

	result.Success = true
	result.PacketLoss = float64(p.pingCount-len(latencies)) / float64(p.pingCount) * 100.0

	// Calculate min, max, avg
	var sum int64
	result.MinLatencyMs = math.MaxInt64
	result.MaxLatencyMs = 0

	for _, lat := range latencies {
		sum += lat
		if lat < result.MinLatencyMs {
			result.MinLatencyMs = lat
		}
		if lat > result.MaxLatencyMs {
			result.MaxLatencyMs = lat
		}
	}

	result.AvgLatencyMs = sum / int64(len(latencies))

	return result
}

// ExecuteTunnelPing executes a tunnel ping task and returns the result.
// This is the main entry point for agents to execute tunnel_ping probe tasks.
func ExecuteTunnelPing(ctx context.Context, task *ProbeTask) *ProbeTaskResult {
	result := &ProbeTaskResult{
		TaskID: task.ID,
		Type:   task.Type,
		RuleID: task.RuleID,
	}

	// Set defaults
	pingCount := task.PingCount
	if pingCount <= 0 {
		pingCount = 3
	}

	pingInterval := task.PingIntervalMs
	if pingInterval <= 0 {
		pingInterval = 200
	}

	connTimeout := time.Duration(task.TunnelConnTimeout) * time.Millisecond
	if connTimeout <= 0 {
		connTimeout = 10 * time.Second
	}

	pingTimeout := time.Duration(task.Timeout) * time.Millisecond
	if pingTimeout <= 0 {
		pingTimeout = 5 * time.Second
	}

	// Determine tunnel type
	tunnelType := TunnelType(task.TunnelType)
	if tunnelType == "" {
		tunnelType = TunnelTypeWS
	}

	// Create pinger
	pinger := NewTunnelPinger(
		task.Target,
		task.Port,
		tunnelType,
		task.TunnelToken,
		task.RuleID,
		WithPingCount(pingCount),
		WithPingInterval(pingInterval),
		WithConnTimeout(connTimeout),
		WithPingTimeout(pingTimeout),
	)

	// Execute ping
	pingResult := pinger.Ping(ctx)

	// Map to result
	result.Success = pingResult.Success
	result.LatencyMs = pingResult.AvgLatencyMs
	result.MinLatencyMs = pingResult.MinLatencyMs
	result.MaxLatencyMs = pingResult.MaxLatencyMs
	result.AvgLatencyMs = pingResult.AvgLatencyMs
	result.PacketLoss = pingResult.PacketLoss
	result.PingsSent = pingResult.PingsSent
	result.PingsRecv = pingResult.PingsRecv
	result.Error = pingResult.Error

	return result
}
