// AUTO-GENERATED - DO NOT EDIT
// Generated by Claude from orris backend
// Source: github.com/orris-inc/orris/sdk/forward

// Package forward provides a Go SDK for interacting with the Orris Forward Agent API.
package forward

// RuleType represents the type of forward rule.
type RuleType string

const (
	// RuleTypeDirect forwards traffic directly to the target.
	RuleTypeDirect RuleType = "direct"
	// RuleTypeEntry is the entry point that forwards traffic to exit agent via WS tunnel.
	// The target information is configured on the entry rule and passed to the exit agent.
	RuleTypeEntry RuleType = "entry"
	// RuleTypeChain is a multi-hop chain forward rule.
	// Traffic flows through multiple agents: entry -> relay1 -> relay2 -> ... -> exit -> target.
	RuleTypeChain RuleType = "chain"
	// RuleTypeDirectChain is a direct chain forward rule that uses direct TCP/UDP connections instead of WS tunnels.
	// Similar to chain but each hop connects directly to the next hop's listen port.
	RuleTypeDirectChain RuleType = "direct_chain"
)

// TunnelType represents the type of tunnel for forwarding traffic.
type TunnelType string

const (
	// TunnelTypeWS represents WebSocket tunnel.
	TunnelTypeWS TunnelType = "ws"
	// TunnelTypeTLS represents TLS tunnel.
	TunnelTypeTLS TunnelType = "tls"
)

// IsWS returns true if this is a WebSocket tunnel (or default).
func (t TunnelType) IsWS() bool {
	return t == TunnelTypeWS || t == ""
}

// IsTLS returns true if this is a TLS tunnel.
func (t TunnelType) IsTLS() bool {
	return t == TunnelTypeTLS
}

// LoadBalanceStrategy represents the load balancing strategy for multi-exit rules.
type LoadBalanceStrategy string

const (
	// LoadBalanceStrategyFailover uses priority-based failover.
	// Agents are tried in order of weight (highest first), with weight=0 as backup.
	LoadBalanceStrategyFailover LoadBalanceStrategy = "failover"

	// LoadBalanceStrategyWeighted distributes traffic based on weight ratios.
	LoadBalanceStrategyWeighted LoadBalanceStrategy = "weighted"
)

// IsFailover returns true if the strategy is failover.
func (s LoadBalanceStrategy) IsFailover() bool {
	return s == LoadBalanceStrategyFailover || s == ""
}

// IsWeighted returns true if the strategy is weighted.
func (s LoadBalanceStrategy) IsWeighted() bool {
	return s == LoadBalanceStrategyWeighted
}

// ExitAgent represents an exit agent with weight for load balancing.
type ExitAgent struct {
	AgentID string `json:"agent_id"` // Stripe-style prefixed ID (e.g., "fa_xK9mP2vL3nQ")
	Weight  uint16 `json:"weight"`   // Weight for load balancing (0-100, 0=backup)
}

// Rule represents a forward rule returned by the API.
// Note: ws_listen_port field has been removed (exit type deprecated).
type Rule struct {
	ID                  string              `json:"id"`                                // Stripe-style prefixed ID (e.g., "fr_xK9mP2vL3nQ")
	AgentID             string              `json:"agent_id"`                          // Stripe-style prefixed ID (e.g., "fa_xK9mP2vL3nQ")
	RuleType            RuleType            `json:"rule_type"`
	ExitAgentID         string              `json:"exit_agent_id,omitempty"`           // Stripe-style prefixed ID (mutually exclusive with ExitAgents)
	ExitAgents          []ExitAgent         `json:"exit_agents,omitempty"`             // For entry type with load balancing (mutually exclusive with ExitAgentID)
	LoadBalanceStrategy LoadBalanceStrategy `json:"load_balance_strategy,omitempty"`   // Load balance strategy: failover (default), weighted
	Name                string              `json:"name"`
	ListenPort    uint16   `json:"listen_port"`
	TargetAddress string   `json:"target_address,omitempty"`
	TargetPort    uint16   `json:"target_port,omitempty"`
	BindIP        string   `json:"bind_ip,omitempty"` // Bind IP address for outbound connections
	Protocol      string   `json:"protocol"`
	Status        string   `json:"status"`
	Remark        string   `json:"remark,omitempty"`
	UploadBytes   int64    `json:"upload_bytes"`
	DownloadBytes int64    `json:"download_bytes"`
	TotalBytes    int64    `json:"total_bytes"`
	CreatedAt     string   `json:"created_at"`
	UpdatedAt     string   `json:"updated_at"`

	// Role indicates the requesting agent's role in this rule
	// Values: "entry" (needs to establish tunnel), "exit" (accepts tunnel connections), "relay" (chain middle node)
	Role string `json:"role,omitempty"`

	// Tunnel configuration
	TunnelType TunnelType `json:"tunnel_type,omitempty"` // Tunnel type: "ws" or "tls" (default: "ws")
	TunnelHops *int       `json:"tunnel_hops,omitempty"` // Number of hops using tunnel (nil=full tunnel, N=first N hops use tunnel)

	// Hop mode for hybrid chain (populated based on agent's position)
	HopMode      string `json:"hop_mode,omitempty"`      // "tunnel", "direct", or "boundary"
	InboundMode  string `json:"inbound_mode,omitempty"`  // For boundary nodes: "tunnel" or "direct"
	OutboundMode string `json:"outbound_mode,omitempty"` // For boundary nodes: "tunnel" or "direct"

	// Chain-specific fields (for chain rule type)
	ChainAgentIDs          []string `json:"chain_agent_ids,omitempty"`           // Ordered list of agent IDs in chain
	ChainPosition          int      `json:"chain_position,omitempty"`            // Agent's position in chain (0-indexed)
	IsLastInChain          bool     `json:"is_last_in_chain,omitempty"`          // True if agent is last in chain
	NextHopAgentID         string   `json:"next_hop_agent_id,omitempty"`         // Next agent in chain
	NextHopAddress         string   `json:"next_hop_address,omitempty"`          // Next agent's public address
	NextHopWsPort          uint16   `json:"next_hop_ws_port,omitempty"`          // Next agent's WS port
	NextHopTlsPort         uint16   `json:"next_hop_tls_port,omitempty"`         // Next agent's TLS port
	NextHopPort            uint16   `json:"next_hop_port,omitempty"`             // Next agent's listen port for direct_chain
	NextHopConnectionToken string   `json:"next_hop_connection_token,omitempty"` // Short-term token for next hop authentication
}

// IsDirect returns true if this is a direct forward rule.
func (r *Rule) IsDirect() bool {
	return r.RuleType == RuleTypeDirect
}

// IsEntry returns true if this is an entry rule.
func (r *Rule) IsEntry() bool {
	return r.RuleType == RuleTypeEntry
}

// IsChain returns true if this is a chain forward rule.
func (r *Rule) IsChain() bool {
	return r.RuleType == RuleTypeChain
}

// IsChainEntry returns true if this agent is the entry point of a chain rule.
func (r *Rule) IsChainEntry() bool {
	return r.RuleType == RuleTypeChain && r.ChainPosition == 0
}

// IsChainRelay returns true if this agent is a relay (middle) node in a chain rule.
func (r *Rule) IsChainRelay() bool {
	return r.RuleType == RuleTypeChain && !r.IsLastInChain && r.ChainPosition > 0
}

// IsChainExit returns true if this agent is the exit (last) node in a chain rule.
func (r *Rule) IsChainExit() bool {
	return r.RuleType == RuleTypeChain && r.IsLastInChain
}

// IsDirectChain returns true if this is a direct_chain forward rule.
func (r *Rule) IsDirectChain() bool {
	return r.RuleType == RuleTypeDirectChain
}

// IsDirectChainEntry returns true if this agent is the entry point of a direct_chain rule.
func (r *Rule) IsDirectChainEntry() bool {
	return r.RuleType == RuleTypeDirectChain && r.ChainPosition == 0
}

// IsDirectChainRelay returns true if this agent is a relay (middle) node in a direct_chain rule.
func (r *Rule) IsDirectChainRelay() bool {
	return r.RuleType == RuleTypeDirectChain && !r.IsLastInChain && r.ChainPosition > 0
}

// IsDirectChainExit returns true if this agent is the exit (last) node in a direct_chain rule.
func (r *Rule) IsDirectChainExit() bool {
	return r.RuleType == RuleTypeDirectChain && r.IsLastInChain
}

// ExitEndpoint represents the connection information for an exit agent.
type ExitEndpoint struct {
	Address string `json:"address"`
	WsPort  uint16 `json:"ws_port"`
	TlsPort uint16 `json:"tls_port"` // TLS tunnel port
}

// RulesResponse represents the response from GetRules API.
type RulesResponse struct {
	Rules       []Rule `json:"rules"`
	ClientToken string `json:"client_token"` // Agent's own token for tunnel handshake (fwd_xxx_xxx format)
	// Note: TokenSigningSecret has been removed for security reasons.
	// Agents should verify tokens via the server API, not using local HMAC verification.
}

// TrafficItem represents traffic data for a single rule.
type TrafficItem struct {
	RuleID        string `json:"rule_id"` // Stripe-style prefixed ID (e.g., "fr_xK9mP2vL3nQ")
	UploadBytes   int64  `json:"upload_bytes"`
	DownloadBytes int64  `json:"download_bytes"`
}

// TrafficReportResult represents the result of a traffic report.
type TrafficReportResult struct {
	RulesUpdated int `json:"rules_updated"`
	RulesFailed  int `json:"rules_failed"`
	RulesDenied  int `json:"rules_denied"` // rules denied due to authorization failure
}

// apiResponse represents the standard API response structure.
type apiResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message,omitempty"`
	Data    any    `json:"data,omitempty"`
}

// AgentStatus represents the status data reported by a forward agent.
type AgentStatus struct {
	// System resources
	CPUPercent    float64 `json:"cpu_percent"`
	MemoryPercent float64 `json:"memory_percent"`
	MemoryUsed    uint64  `json:"memory_used"`
	MemoryTotal   uint64  `json:"memory_total"`
	MemoryAvail   uint64  `json:"memory_avail"`
	DiskPercent   float64 `json:"disk_percent"`
	DiskUsed      uint64  `json:"disk_used"`
	DiskTotal     uint64  `json:"disk_total"`
	UptimeSeconds int64   `json:"uptime_seconds"`

	// System load average
	LoadAvg1  float64 `json:"load_avg_1"`
	LoadAvg5  float64 `json:"load_avg_5"`
	LoadAvg15 float64 `json:"load_avg_15"`

	// Network statistics
	NetworkRxBytes uint64 `json:"network_rx_bytes"` // Total received bytes
	NetworkTxBytes uint64 `json:"network_tx_bytes"` // Total transmitted bytes
	NetworkRxRate  uint64 `json:"network_rx_rate"`  // Current receive rate (bytes/sec)
	NetworkTxRate  uint64 `json:"network_tx_rate"`  // Current transmit rate (bytes/sec)

	// Network connections
	TCPConnections int `json:"tcp_connections"`
	UDPConnections int `json:"udp_connections"`

	// Public IP addresses
	PublicIPv4 string `json:"public_ipv4,omitempty"`
	PublicIPv6 string `json:"public_ipv6,omitempty"`

	// Agent info
	AgentVersion string `json:"agent_version,omitempty"` // Agent software version (e.g., "1.2.3")
	Platform     string `json:"platform,omitempty"`      // OS platform (linux, darwin, windows)
	Arch         string `json:"arch,omitempty"`          // CPU architecture (amd64, arm64, arm, 386)

	// CPU details
	CPUCores     int     `json:"cpu_cores"`      // Number of CPU cores
	CPUModelName string  `json:"cpu_model_name"` // CPU model name
	CPUMHz       float64 `json:"cpu_mhz"`        // CPU frequency in MHz

	// Swap memory
	SwapTotal   uint64  `json:"swap_total"`   // Total swap in bytes
	SwapUsed    uint64  `json:"swap_used"`    // Used swap in bytes
	SwapPercent float64 `json:"swap_percent"` // Swap usage percentage

	// Disk I/O
	DiskReadBytes  uint64 `json:"disk_read_bytes"`  // Total disk read bytes
	DiskWriteBytes uint64 `json:"disk_write_bytes"` // Total disk write bytes
	DiskReadRate   uint64 `json:"disk_read_rate"`   // Disk read rate in bytes per second
	DiskWriteRate  uint64 `json:"disk_write_rate"`  // Disk write rate in bytes per second
	DiskIOPS       uint64 `json:"disk_iops"`        // Disk IOPS

	// Pressure Stall Information (PSI)
	PSICPUSome    float64 `json:"psi_cpu_some"`    // CPU pressure (some)
	PSICPUFull    float64 `json:"psi_cpu_full"`    // CPU pressure (full)
	PSIMemorySome float64 `json:"psi_memory_some"` // Memory pressure (some)
	PSIMemoryFull float64 `json:"psi_memory_full"` // Memory pressure (full)
	PSIIOSome     float64 `json:"psi_io_some"`     // I/O pressure (some)
	PSIIOFull     float64 `json:"psi_io_full"`     // I/O pressure (full)

	// Network extended stats
	NetworkRxPackets uint64 `json:"network_rx_packets"` // Received packets
	NetworkTxPackets uint64 `json:"network_tx_packets"` // Transmitted packets
	NetworkRxErrors  uint64 `json:"network_rx_errors"`  // Receive errors
	NetworkTxErrors  uint64 `json:"network_tx_errors"`  // Transmit errors
	NetworkRxDropped uint64 `json:"network_rx_dropped"` // Receive dropped packets
	NetworkTxDropped uint64 `json:"network_tx_dropped"` // Transmit dropped packets

	// Socket statistics
	SocketsUsed      int `json:"sockets_used"`       // Total used sockets
	SocketsTCPInUse  int `json:"sockets_tcp_in_use"` // TCP sockets in use
	SocketsUDPInUse  int `json:"sockets_udp_in_use"` // UDP sockets in use
	SocketsTCPOrphan int `json:"sockets_tcp_orphan"` // TCP orphan connections
	SocketsTCPTW     int `json:"sockets_tcp_tw"`     // TCP TIME_WAIT connections

	// Process statistics
	ProcessesTotal   uint64 `json:"processes_total"`   // Total processes
	ProcessesRunning uint64 `json:"processes_running"` // Running processes
	ProcessesBlocked uint64 `json:"processes_blocked"` // Blocked processes

	// File descriptors
	FileNrAllocated uint64 `json:"file_nr_allocated"` // Allocated file descriptors
	FileNrMax       uint64 `json:"file_nr_max"`       // Maximum file descriptors

	// Context switches and interrupts
	ContextSwitches uint64 `json:"context_switches"` // Context switches count
	Interrupts      uint64 `json:"interrupts"`       // Interrupts count

	// Kernel info
	KernelVersion string `json:"kernel_version"` // Kernel version
	Hostname      string `json:"hostname"`       // System hostname

	// Virtual memory statistics
	VMPageIn  uint64 `json:"vm_page_in"`  // Pages paged in
	VMPageOut uint64 `json:"vm_page_out"` // Pages paged out
	VMSwapIn  uint64 `json:"vm_swap_in"`  // Swap pages in
	VMSwapOut uint64 `json:"vm_swap_out"` // Swap pages out
	VMOOMKill uint64 `json:"vm_oom_kill"` // OOM kill count

	// Entropy pool
	EntropyAvailable uint64 `json:"entropy_available"` // Available entropy

	// Forward status
	ActiveRules       int                    `json:"active_rules"`
	ActiveConnections int                    `json:"active_connections"`
	TunnelStatus      map[string]TunnelState `json:"tunnel_status,omitempty"` // Key is Stripe-style rule ID (e.g., "fr_xK9mP2vL3nQ")

	// Tunnel configuration (for exit agent)
	// Note: Tunnel ports are now reported directly by the agent in status updates,
	// not configured per-rule (exit rule type has been removed).
	WsListenPort  uint16 `json:"ws_listen_port,omitempty"`  // WebSocket listen port for tunnel connections
	TlsListenPort uint16 `json:"tls_listen_port,omitempty"` // TLS listen port for tunnel connections
}

// TunnelState represents the connection state of a tunnel.
type TunnelState string

const (
	TunnelStateConnected    TunnelState = "connected"
	TunnelStateConnecting   TunnelState = "connecting"
	TunnelStateDisconnected TunnelState = "disconnected"
)

// ProbeTaskType represents the type of probe task.
type ProbeTaskType string

const (
	// ProbeTaskTypeTarget probes target reachability from agent.
	ProbeTaskTypeTarget ProbeTaskType = "target"
	// ProbeTaskTypeTunnel probes tunnel connectivity (entry to exit) via TCP connection test.
	ProbeTaskTypeTunnel ProbeTaskType = "tunnel"
	// ProbeTaskTypeTunnelPing measures tunnel latency by sending ping/pong through the tunnel.
	ProbeTaskTypeTunnelPing ProbeTaskType = "tunnel_ping"
)

// ProbeTask represents a probe task to be executed by the agent.
type ProbeTask struct {
	ID       string        `json:"id"`
	Type     ProbeTaskType `json:"type"`
	RuleID   string        `json:"rule_id"` // Stripe-style prefixed ID (e.g., "fr_xK9mP2vL3nQ")
	Target   string        `json:"target"`
	Port     uint16        `json:"port"`
	Protocol string        `json:"protocol"` // always "tcp"
	Timeout  int           `json:"timeout"`  // milliseconds

	// TunnelPing specific fields
	TunnelType        string `json:"tunnel_type,omitempty"`         // "ws" or "tls"
	TunnelToken       string `json:"tunnel_token,omitempty"`        // connection token for tunnel handshake
	PingCount         int    `json:"ping_count,omitempty"`          // number of pings (default: 3)
	PingIntervalMs    int    `json:"ping_interval_ms,omitempty"`    // interval between pings in ms (default: 200)
	TunnelConnTimeout int    `json:"tunnel_conn_timeout,omitempty"` // tunnel connection timeout in ms
}

// ProbeTaskResult represents the result of a probe task execution.
type ProbeTaskResult struct {
	TaskID    string        `json:"task_id"`
	Type      ProbeTaskType `json:"type"`
	RuleID    string        `json:"rule_id"` // Stripe-style prefixed ID (e.g., "fr_xK9mP2vL3nQ")
	Success   bool          `json:"success"`
	LatencyMs int64         `json:"latency_ms"`
	Error     string        `json:"error,omitempty"`

	// TunnelPing specific results
	MinLatencyMs int64   `json:"min_latency_ms,omitempty"` // minimum RTT
	MaxLatencyMs int64   `json:"max_latency_ms,omitempty"` // maximum RTT
	AvgLatencyMs int64   `json:"avg_latency_ms,omitempty"` // average RTT
	PacketLoss   float64 `json:"packet_loss,omitempty"`    // packet loss percentage (0-100)
	PingsSent    int     `json:"pings_sent,omitempty"`     // number of pings sent
	PingsRecv    int     `json:"pings_recv,omitempty"`     // number of pongs received
}

// ProbeMessage is the WebSocket message envelope for probe communication.
type ProbeMessage struct {
	Type string `json:"type"`
	Data any    `json:"data"`
}

// ProbeMessageType constants for WebSocket message types.
const (
	ProbeMessageTypeTask   = "task"
	ProbeMessageTypeResult = "result"
)

// TunnelHandshake is sent by entry agent to exit agent when establishing a tunnel connection.
// The exit agent should verify the token and check if the rule allows this connection.
type TunnelHandshake struct {
	AgentToken string `json:"agent_token"`          // Entry agent's HMAC-based token for verification
	RuleID     string `json:"rule_id"`              // The rule this connection belongs to (e.g., "fr_xK9mP2vL3nQ")
	IsProbe    bool   `json:"is_probe,omitempty"`   // True if this is a probe connection (tunnel ping)
}

// TunnelHandshakeResult is sent by exit agent back to entry agent after verification.
type TunnelHandshakeResult struct {
	Success      bool   `json:"success"`
	Error        string `json:"error,omitempty"`
	EntryAgentID string `json:"entry_agent_id,omitempty"` // Verified entry agent ID (e.g., "fa_xK9mP2vL3nQ")
}

// RuleSyncStatusItem represents the sync and runtime status of a single forward rule.
type RuleSyncStatusItem struct {
	RuleID       string `json:"rule_id"`       // Stripe-style rule ID (e.g., "fr_xK9mP2vL3nQ")
	SyncStatus   string `json:"sync_status"`   // Sync status: synced, pending, failed
	RunStatus    string `json:"run_status"`    // Runtime status: running, stopped, error, starting
	ListenPort   uint16 `json:"listen_port"`   // Actual listening port
	Connections  int    `json:"connections"`   // Current number of connections
	ErrorMessage string `json:"error_message"` // Error message if any
	SyncedAt     int64  `json:"synced_at"`     // Last sync timestamp (Unix seconds)
}

// Rule sync status constants.
const (
	// SyncStatus values.
	SyncStatusSynced  = "synced"
	SyncStatusPending = "pending"
	SyncStatusFailed  = "failed"

	// RunStatus values.
	RunStatusRunning  = "running"
	RunStatusStopped  = "stopped"
	RunStatusError    = "error"
	RunStatusStarting = "starting"
)

// TunnelHealthReport represents a tunnel health status report from entry agent.
// Entry agents periodically check tunnel connectivity to exit agents and report failures.
// Used with MsgTypeTunnelHealthReport message type via HubConn.SendTunnelHealthReport().
type TunnelHealthReport struct {
	RuleID      string `json:"rule_id"`                // Rule ID (Stripe-style prefixed, e.g., "fr_xxx")
	ExitAgentID string `json:"exit_agent_id"`          // Exit agent ID (Stripe-style prefixed, e.g., "fa_xxx")
	Healthy     bool   `json:"healthy"`                // Whether the tunnel is healthy
	FailCount   int    `json:"fail_count,omitempty"`   // Consecutive failure count (when unhealthy)
	Error       string `json:"error,omitempty"`        // Error message (when unhealthy)
	LatencyMs   *int64 `json:"latency_ms,omitempty"`   // Last measured latency in milliseconds (when healthy)
	CheckedAt   int64  `json:"checked_at"`             // Health check timestamp (Unix seconds)
}
